// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

void test_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Main
void ui_Main_screen_init(void);
void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
// SCREEN: ui_Scan
void ui_Scan_screen_init(void);
extern lv_obj_t * ui_Scan;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Scan_Image1;
void ui_event_Scan_Button2(lv_event_t * e);
extern lv_obj_t * ui_Scan_Button2;
// SCREEN: ui_Records
void ui_Records_screen_init(void);
extern lv_obj_t * ui_Records;
void ui_event_Records_Roller4(lv_event_t * e);
extern lv_obj_t * ui_Records_Roller4;
extern lv_obj_t * ui_Records_Label4;
void ui_event_Back(lv_event_t * e);
extern lv_obj_t * ui_Back;
// SCREEN: ui_Setup
void ui_Setup_screen_init(void);
extern lv_obj_t * ui_Setup;
extern lv_obj_t * ui_Test_Button2;
extern lv_obj_t * ui_RFIDScanner;
extern lv_obj_t * ui_Test_Dropdown1;
extern lv_obj_t * ui_Test_Switch1;
extern lv_obj_t * ui_Test_Panel1;
extern lv_obj_t * ui_Test_Info_Bar;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_SDCard;
extern lv_obj_t * ui_RFID;
extern lv_obj_t * ui_WiFi;
extern lv_obj_t * ui_Bluetooth;
extern lv_obj_t * ui_Battery;
extern lv_obj_t * ui_WiFIAP;
void ui_event_Back1(lv_event_t * e);
extern lv_obj_t * ui_Back1;
// SCREEN: ui_Test1
void ui_Test1_screen_init(void);
extern lv_obj_t * ui_Test1;
void ui_event_Test1_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Test1_Keyboard1;
extern lv_obj_t * ui_Test1_Calendar1;
extern lv_obj_t * ui_Test1_TextArea2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_sheep_png);    // assets/sheep.png
LV_IMG_DECLARE(ui_img_arrow_back_fill0_wght500_grad0_opsz48_png);    // assets/arrow_back_FILL0_wght500_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_contactless_fill0_wght500_grad0_opsz48_png);    // assets/contactless_FILL0_wght500_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_contactless_off_fill0_wght500_grad0_opsz48_png);    // assets/contactless_off_FILL0_wght500_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_sd_card_alert_fill0_wght500_grad0_opsz48_png);    // assets/sd_card_alert_FILL0_wght500_GRAD0_opsz48.png
LV_IMG_DECLARE(ui_img_wifi_off_png);    // assets/wifi_off.png
LV_IMG_DECLARE(ui_img_bluetooth_connected_png);    // assets/bluetooth_connected.png
LV_IMG_DECLARE(ui_img_battery_charging_20_png);    // assets/battery_charging_20.png
LV_IMG_DECLARE(ui_img_wifi_tethering_png);    // assets/wifi_tethering.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
