// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Records_screen_init(void)
{
    ui_Records = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Records, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Records_Roller4 = lv_roller_create(ui_Records);
    lv_roller_set_options(ui_Records_Roller4,
                          "\nAUS000111111\nAUS022222222\nAUS000112222\nAUS000055500\nAUS000111333\nAUS000666100\nAUS012345600",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Records_Roller4, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_Records_Roller4, lv_pct(100));
    lv_obj_set_height(ui_Records_Roller4, lv_pct(80));
    lv_obj_set_x(ui_Records_Roller4, 1);
    lv_obj_set_y(ui_Records_Roller4, lv_pct(10));
    lv_obj_set_align(ui_Records_Roller4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Records_Roller4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_text_font(ui_Records_Roller4, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Records_Roller4, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_text_font(ui_Records_Roller4, &lv_font_montserrat_48, LV_PART_SELECTED | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Records_Roller4, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_Records_Roller4, LV_PART_SELECTED | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Grey);

    ui_Records_Label4 = lv_label_create(ui_Records);
    lv_obj_set_width(ui_Records_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Records_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Records_Label4, -45);
    lv_obj_set_y(ui_Records_Label4, lv_pct(-41));
    lv_obj_set_align(ui_Records_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Records_Label4, "Records ...");
    lv_obj_add_state(ui_Records_Label4, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_font(ui_Records_Label4, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back = lv_btn_create(ui_Records);
    lv_obj_set_width(ui_Back, 80);
    lv_obj_set_height(ui_Back, 80);
    lv_obj_set_x(ui_Back, -5);
    lv_obj_set_y(ui_Back, -5);
    lv_obj_set_align(ui_Back, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Back, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Back, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Grey);
    ui_object_set_themeable_style_property(ui_Back, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Grey);
    lv_obj_set_style_bg_grad_color(ui_Back, lv_color_hex(0x8F8F8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Back, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Back, &ui_img_arrow_back_fill0_wght500_grad0_opsz48_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Records_Roller4, ui_event_Records_Roller4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Back, ui_event_Back, LV_EVENT_ALL, NULL);

}
