// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Scan_screen_init(void)
{
    ui_Scan = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Scan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Scan);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -4);
    lv_obj_set_y(ui_Label3, 65);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Scan ...");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scan_Image1 = lv_img_create(ui_Scan);
    lv_img_set_src(ui_Scan_Image1, &ui_img_sheep_png);
    lv_obj_set_width(ui_Scan_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scan_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scan_Image1, 5);
    lv_obj_set_y(ui_Scan_Image1, -163);
    lv_obj_set_align(ui_Scan_Image1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Scan_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_zoom(ui_Scan_Image1, 100);

    ui_Scan_Button2 = lv_btn_create(ui_Scan);
    lv_obj_set_width(ui_Scan_Button2, 120);
    lv_obj_set_height(ui_Scan_Button2, 120);
    lv_obj_set_x(ui_Scan_Button2, -5);
    lv_obj_set_y(ui_Scan_Button2, -5);
    lv_obj_set_align(ui_Scan_Button2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Scan_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Scan_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Scan_Button2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Scan_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Blue);
    ui_object_set_themeable_style_property(ui_Scan_Button2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Blue);
    lv_obj_set_style_bg_img_src(ui_Scan_Button2, &ui_img_1420163004, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Scan_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Scan_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Scan_Button2, ui_event_Scan_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Scan, ui_event_Scan, LV_EVENT_ALL, NULL);

}
