// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Test1_screen_init(void)
{
    ui_Test1 = lv_obj_create(NULL);
    lv_obj_add_state(ui_Test1, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_Test1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Test1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags

    ui_Test1_Keyboard1 = lv_keyboard_create(ui_Test1);
    lv_obj_set_width(ui_Test1_Keyboard1, lv_pct(100));
    lv_obj_set_height(ui_Test1_Keyboard1, lv_pct(25));
    lv_obj_set_x(ui_Test1_Keyboard1, 0);
    lv_obj_set_y(ui_Test1_Keyboard1, 225);
    lv_obj_set_align(ui_Test1_Keyboard1, LV_ALIGN_CENTER);

    ui_Test1_Calendar1 = lv_calendar_create(ui_Test1);
    lv_calendar_set_today_date(ui_Test1_Calendar1, 2024, 4, 19);
    lv_calendar_set_showed_date(ui_Test1_Calendar1, 2024, 4);
    lv_obj_t * ui_Test1_Calendar1_header = lv_calendar_header_arrow_create(ui_Test1_Calendar1);
    lv_obj_set_width(ui_Test1_Calendar1, lv_pct(100));
    lv_obj_set_height(ui_Test1_Calendar1, lv_pct(65));
    lv_obj_set_x(ui_Test1_Calendar1, 0);
    lv_obj_set_y(ui_Test1_Calendar1, lv_pct(-17));
    lv_obj_set_align(ui_Test1_Calendar1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Test1_Calendar1, LV_STATE_PRESSED);       /// States

    lv_obj_set_style_outline_color(ui_Test1_Calendar1, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Test1_Calendar1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Test1_Calendar1, 5, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Test1_Calendar1, 0, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Test1_TextArea2 = lv_textarea_create(ui_Test1);
    lv_obj_set_width(ui_Test1_TextArea2, lv_pct(100));
    lv_obj_set_height(ui_Test1_TextArea2, lv_pct(10));
    lv_obj_set_x(ui_Test1_TextArea2, lv_pct(0));
    lv_obj_set_y(ui_Test1_TextArea2, lv_pct(65));
    lv_obj_set_align(ui_Test1_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Test1_TextArea2, "Placeholder...");



    lv_obj_add_event_cb(ui_Test1_Keyboard1, ui_event_Test1_Keyboard1, LV_EVENT_ALL, NULL);

}
